language: "perl"
perl:
  - "5.20"

script: "cpanm --installdeps . && perl Makefile.PL && make test && make install && find $start_with -name story.rb -or -name story.bash -or -name story.pl -execdir pwd \; "
